[package]
name = "hello_canado"
version = "1.0.0"
authors = []

[addresses]
coin_address="0x8549fd85ef6509f212b306ae3d265049f6ddb2ac8b016e02b8c1882615f38a5a"
user_public="0xd5f021cfbd78705f6e3fc5af2ab0ef20b80ee57c5aef8003d2b996d006e35b27"
user_address="0x41"
hello_contract="0x8549fd85ef6509f212b306ae3d265049f6ddb2ac8b016e02b8c1882615f38a5a"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
